# Generated by Django 5.2.5 on 2025-09-02 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_alter_tarea_reponsable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='reponsable',
            new_name='responsable',
        ),
    ]
